### ISSUE TITLE
Test report Scratch 1st of Oct. 18

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/scratch-vm#17] opened 2018-10-01 15:17 UTC
I tested a few things on a Windows 8.1 machine, Chrome, Wireless Thymio and classic Thymio:

1. When connecting to the Thymio extension, the forward or left arrow LED is always lit on. It does that on Wireless and classic Thymio. Sometimes it's the forward, sometimes the left. It's really when the scratch extension connects to Thymio not the web bridge or anything else. Some LEDs blink (like the circle ones) and then, one of the button LED lights on and stays like that. 
I found a funny thing with that. If you just use this block:
![image](https://user-images.githubusercontent.com/4930020/46296462-b65d3f80-c59a-11e8-806d-cfd89b1098bd.png)
and click on it, the button LED that is next to the one always lit light up a bit (like half of power) and when the motors are stopping the LED that was lit turns off and the one that was half lit lights up completely. It does some sort of a circle, one LED after the other.
You can also do that with this block:
![image](https://user-images.githubusercontent.com/4930020/46296678-37b4d200-c59b-11e8-9e2b-4a487e724080.png)

2. Leds clear => doesn't clear the horizontal sensors LEDs

3. leds buttons => just blink and does not stay as you ask. Doesn't fix the constant lit on LED either

4. Should we add a "is pressed" at the end of the button event?
![image](https://user-images.githubusercontent.com/4930020/46295599-c411c580-c598-11e8-8371-272d1a153abc.png)

5. While using a Wireless Thymio, some commands are sent but are not executed by the robot. Doesn't happen with classic Thymio. I did this simple program: 
![image](https://user-images.githubusercontent.com/4930020/46295705-04714380-c599-11e8-85b2-8145817ad67e.png)
and saw a ~10% time failure on one of the two motors. Also happens if you just command one motor, sometimes it doesn't stop or doesn't turn on. 
it's problematic on some occasion such as this one:
![image](https://user-images.githubusercontent.com/4930020/46296805-7fd3f480-c59b-11e8-8823-e703c4d77fb8.png)
The robot just stops after X movements and doesn't go back in the loop. I tried with all the three channels and the problem occurs in each three of them. Sometimes it's after 5 loops, sometimes, you can do 20, but in the end, it always stops.

6. With the "turn X° in Y sec", you can put negative time and it seems to do the same thing as positive time:
![image](https://user-images.githubusercontent.com/4930020/46295955-911c0180-c599-11e8-947c-e5587145fb7b.png)

![image](https://user-images.githubusercontent.com/4930020/46295975-9a0cd300-c599-11e8-925f-f11d2260c132.png)
Couldn't we block some values? Like only positive? Just do some sort of absolute value?
Same thing with smaller than 0 values. For example, I program my robot to turn 90° in 3 seconds:
![image](https://user-images.githubusercontent.com/4930020/46296133-f5d75c00-c599-11e8-9a01-deace5f2e22b.png)
It works nicely. Then I decide to go much faster and put 0.5 seconds instead:
![image](https://user-images.githubusercontent.com/4930020/46296113-ebb55d80-c599-11e8-88d2-50c40a4bcee9.png)
And it does the 3 seconds one. Even if I change the value of the angle, the robot does the same thing all over again. It's only when I put back a bigger than 1 value that it does what I want. But I get no warning or anything.

One good point is that the connection is much more stable than before and the delay between orders and execution is much smaller (I had around 10-15ms max)

**Comment by mbonani** [comment] 2018-10-02 14:50
> I tested a few things on a Windows 8.1 machine, Chrome, Wireless Thymio and classic Thymio:
> 
> 1. When connecting to the Thymio extension, the forward or left arrow LED is always lit on. It does that on Wireless and classic Thymio. Sometimes it's the forward, sometimes the left. It's really when the scratch extension connects to Thymio not the web bridge or anything else. Some LEDs blink (like the circle ones) and then, one of the button LED lights on and stays like that.
>    I found a funny thing with that. If you just use this block:
>    ![image](https://user-images.githubusercontent.com/4930020/46296462-b65d3f80-c59a-11e8-806d-cfd89b1098bd.png)
>    and click on it, the button LED that is next to the one always lit light up a bit (like half of power) and when the motors are stopping the LED that was lit turns off and the one that was half lit lights up completely. It does some sort of a circle, one LED after the other.
>    You can also do that with this block:
>    ![image](https://user-images.githubusercontent.com/4930020/46296678-37b4d200-c59b-11e8-9e2b-4a487e724080.png)

Actually it is not a bug because it is a written feature. It is manage by the robot aesl code that show the completion of sequence of movement
Should be discuss if we keep it. 
Related to issue #14 

> 2. Leds clear => doesn't clear the horizontal sensors LEDs
that true, but if you also do a led clear of horizontal sensor LED even if you never put this by your self you will loose the automatic behaviour of this led showing the sensor activity
related to issue #13 

> 3. leds buttons => just blink and does not stay as you ask. Doesn't fix the constant lit on LED either
same as point 1 issue #14 

> 4. Should we add a "is pressed" at the end of the button event?
>    ![image](https://user-images.githubusercontent.com/4930020/46295599-c411c580-c598-11e8-8371-272d1a153abc.png)

the idea of Didier was to not make long phrases when it is not necessary, for me it is obvious so I say no.

> 5. While using a Wireless Thymio, some commands are sent but are not executed by the robot. Doesn't happen with classic Thymio. I did this simple program:
>    ![image](https://user-images.githubusercontent.com/4930020/46295705-04714380-c599-11e8-85b2-8145817ad67e.png)
>    and saw a ~10% time failure on one of the two motors. Also happens if you just command one motor, sometimes it doesn't stop or doesn't turn on.
>    it's problematic on some occasion such as this one:
>    ![image](https://user-images.githubusercontent.com/4930020/46296805-7fd3f480-c59b-11e8-8823-e703c4d77fb8.png)
>    The robot just stops after X movements and doesn't go back in the loop. I tried with all the three channels and the problem occurs in each three of them. Sometimes it's after 5 loops, sometimes, you can do 20, but in the end, it always stops.

We should improve this. It is working well with wired Thymio

> 6. With the "turn X° in Y sec", you can put negative time and it seems to do the same thing as positive time:
>    ![image](https://user-images.githubusercontent.com/4930020/46295955-911c0180-c599-11e8-947c-e5587145fb7b.png)
> 
> ![image](https://user-images.githubusercontent.com/4930020/46295975-9a0cd300-c599-11e8-925f-f11d2260c132.png)
> Couldn't we block some values? Like only positive? Just do some sort of absolute value?

The blocks takes the absolute value, so it is working with negative one, but I am not sure we can modify back the value inserted

> Same thing with smaller than 0 values. For example, I program my robot to turn 90° in 3 seconds:
> ![image](https://user-images.githubusercontent.com/4930020/46296133-f5d75c00-c599-11e8-9a01-deace5f2e22b.png)
> It works nicely. Then I decide to go much faster and put 0.5 seconds instead:
> ![image](https://user-images.githubusercontent.com/4930020/46296113-ebb55d80-c599-11e8-88d2-50c40a4bcee9.png)
> And it does the 3 seconds one. Even if I change the value of the angle, the robot does the same thing all over again. It's only when I put back a bigger than 1 value that it does what I want. But I get no warning or anything.

This is strange yes, not sure what is appening

> 
> One good point is that the connection is much more stable than before and the delay between orders and execution is much smaller (I had around 10-15ms max)

Thank for all who worked toward this

**Comment by mbonani** [comment] 2019-03-02 11:25
I will close this general issue most point are reported in other.

**Closed as completed by mbonani** 2019-03-02 11:25 UTC
